### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by mhetreramesh** [fullstackworld/fullstackworld.com#4]
About Us Page:

It will be simple content page with full width on the frontend. I would prefer to create pages controller & route like Tags, Posts controller.

There is a pages module in the backed where we can just create new page (`/wink/pages`). 

The updated content will be placed [here](https://github.com/fullstackworld/fullstackworld.com/wiki/About/) on the wiki page.

**Comment by juancarmo** [comment]
Need more info about this issue.

Location of the link to access this section.
Information inside the section.

**Comment by mhetreramesh** [comment]
https://fullstackworld.com/page/about
